# Generated by Django 4.0.3 on 2022-03-30 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_timezone',
            field=models.CharField(max_length=32, verbose_name='Часовой пояс'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате 7XXXXXXXXXX (X - цифра от 0 до 9)', regex='^7\\d{9,10}$')], verbose_name='Телефон'),
        ),
    ]
