# Generated by Django 4.0.3 on 2022-03-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_client_timezone_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_timezone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Часовой пояс'),
        ),
    ]
