# Generated by Django 4.0.3 on 2022-03-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_client_client_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст рассылки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tag',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тэг'),
        ),
    ]
