# Generated by Django 4.0.3 on 2022-03-31 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mailinglist_client_operator_mailinglist_client_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='message',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='api.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mailing_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='api.mailinglist', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус отправки'),
        ),
    ]
