# Generated by Django 4.0.3 on 2022-03-31 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_message_added_alter_message_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='api.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mailing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='api.mailinglist', verbose_name='Рассылка'),
        ),
    ]
