# Generated by Django 4.0.3 on 2022-04-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_message_customer_alter_message_mailing_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='job_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер работы планировщика'),
        ),
    ]
